### PR TITLE
Use oops for error handling

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by hasufell** [comment]
Why not excepts? I believe it's more mature.

**Comment by newhoggy** [comment]
> Why not excepts? I believe it's more mature.

I tried that first but I didn't get very far.  One of the reasons I couldn't get it working is there isn't a combinator that preserves the transformer stack.  See `snatchM`, which is the same as `catchM` except the exception is not plucked from the list of possible errors.

There are possibly other reasons like support for `MonadError`, decent error messages, good type inference, flipped catch arguments (which has better ergonomics).

**Comment by hasufell** [comment]
> One of the reasons I couldn't get it working is there isn't a combinator that preserves the transformer stack. See snatchM, which is the same as catchM except the exception is not plucked from the list of possible errors.

Not sure I understand what you mean with preserving the transformer stack. Are you looking for [onE](https://hackage.haskell.org/package/haskus-utils-variant-3.3/docs/Haskus-Utils-Variant-Excepts.html#v:onE)?

> There are possibly other reasons like support for MonadError, decent error messages, good type inference, flipped catch arguments (which has better ergonomics).

Upstream has been responsive and willing to add new instances: https://github.com/haskus/packages/issues/34

Good type inference isn't really possible with open sum types.

**Comment by newhoggy** [comment]
`onE` seems right.

Let me finish this restructuring and we can take a step back and re-evaluate.

**Comment by newhoggy** [comment]
This is coded up.  Next step is to add some integration tests.

**Comment by newhoggy** [comment]
Includes integration tests now, so I'm more comfortable with refactoring not breaking anything accidentally.

**Comment by newhoggy** [comment]
Removed all the pre-oops code.

This PR is ready.

**Comment by prednaz** [comment]
may i ask why you do not just use `plucky`? `oops` is just another implementation of the same interface.

**Comment by newhoggy** [comment]
`plucky` was actually the first out of many libraries I tried.  I found it had poor error messages and type inference (for example using HLS to infer type signatures) was poor which made it difficult to use.

`oops` also has catch combinators with flipped arguments, which is preferable because because it allows me to cleanly stack multiple handlers on the same expression without using parentheses.  The reliance of parentheses is particularly problematic because adding or removing handlers touches more lines than I'd like.

**Comment by newhoggy** [comment]
I wrote some extensive notes on why I chose to go with `oops` in another PR: https://github.com/input-output-hk/cardano-node/pull/4777

**Pull request merged**
