### PR TITLE
Restrictive retry

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Review by newhoggy — APPROVED** [review]

**Comment by hasufell** [comment]
This supersedes #204

**Comment by newhoggy** [comment]
Do you need a release with this?

**Comment by newhoggy** [comment]
Do you have. a Hackage handle?  I can add you as a maintainer.

**Comment by hasufell** [comment]
I'm gonna test binaries later today. I build them from the repo anyway.

**Comment by hasufell** [comment]
> Do you have a Hackage handle?  I can add you as a maintainer.

Sure, maerwald.

**Comment by hasufell** [comment]
Odd. It seems this PR broke `sync-to-archive`, which now gives me 404.

```
cabal-cache sync-to-archive --host-name-override=ap-south-1.linodeobjects.com
--host-port-override=443 --host-ssl-override=True --region ap-south-1 --archive-uri s3://tmp
Store path: /home/hasufell/.cabal/store
Store path hash: 1ea26cde9d
Archive URI: s3://tmp
Archive version: v2
Threads: 4
AWS Log level: Nothing
Syncing 153 packages
Temp path: "/tmp/cabal-cache-635909af7e48f7b4"
cabal-cache: ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 404, statusMessage = "Not Found"}, _serviceHeaders = [("Date","Fri, 30 Dec 2022 13:24:55 GMT"),("Content-Type","application/xml"),("Content-Length","216"),("Connection","keep-alive"),("x-amz-request-id","tx00000000000000148f975-0063aee6a7-56d15b9-default"),("Accept-Ranges","bytes")], _serviceCode = ErrorCode "Not Found", _serviceMessage = Nothing, _serviceRequestId = Just (RequestId "tx00000000000000148f975-0063aee6a7-56d15b9-default")})
```

With the old cabal-cache, it works.

**Pull request merged**
